batch_size: 32
height: 32
learning_rate: 0.001
max_text_length: 21
model_path: Models/03_handwriting_recognition/202512301446
train_epochs: 100
train_workers: 20
vocab: '"Am,yN)7HSZa8RQklCf!?c''p0Gqow6r-Kg:2WO&Db/.xY+ditUIeJzj5(EF3Lu#9VX1*PsvhBn4;TM'
width: 128
