batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition/202512291853
train_epochs: 5
train_workers: 20
vocab: Oa&3290mkqlIwx8:(),ubXhUs.Zg+!?jnSr"*4ATK5dLQWDf7#MN6HPFpo/yEtBYzVc-;'CvJeRiG1
width: 128
